apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: apps

  annotations:
    # 👇 Tell Image Updater which image to watch
    argocd-image-updater.argoproj.io/image-list: user-service=registry.disapp.net:5000/user-service

    # 👇 Automatically pick newest version
    argocd-image-updater.argoproj.io/update-strategy: semver

    # 👇 Write back updated image to Git
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          # ⚠️ INITIAL VERSION ONLY (will be auto-updated later)
          image: registry.disapp.net:5000/user-service

          imagePullPolicy: Always

          ports:
            - containerPort: 8080