apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: user-service=registry.disapp.net:5000/user-service
    argocd-image-updater.argoproj.io/user-service.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          # 👇 DO NOT pin version (Image Updater will update this)
          image: registry.disapp.net:5000/user-service

          imagePullPolicy: Always

          ports:
            - containerPort: 8080